# Generated by Django 5.2.17 on 2026-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
