# Generated by Django 5.2.17 on 2026-09-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_split_experience_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
